node {
    docker.image('node:16-buster-slim').inside('-p 3000:3000') {

        stage('Build') {
            sh 'npm install'
            sh 'npm run build'
        }

        stage('Test') {
            sh './jenkins/scripts/test.sh'
        }

        stage('Deploy') {
            sh '''
                echo "Deploying application..."
                # contoh: copy hasil build ke folder tertentu
                # cp -r build/* /var/www/html/

                # atau jalankan script deploy custom
                # ./jenkins/scripts/deploy.sh
            '''
        }
    }
}
